# Generated by Django 3.1.3 on 2020-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.URLField(),
        ),
    ]
