# Generated by Django 3.1.3 on 2020-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20201122_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='full_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.URLField(max_length=300),
        ),
    ]
