# Generated by Django 3.1.3 on 2020-11-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20201122_0200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='URLs',
        ),
    ]
